# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='birth_date',
            field=models.DateField(default='1994-05-26'),
            preserve_default=False,
        ),
    ]
